version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Backend Test for Free-now'
            echo 'This is the delivery pipeline'
